title: infraguide.org
description: Open Source Infrastructure – Guides, Tools and Training.
url: "https://infraguide.org"
baseurl: ""

author: Vladislav Nazarenko

markdown: kramdown
highlighter: rouge

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
